var Paper2SlideSummarizer = {
    /**
     * Summarizes the text content into slide-sized chunks.
     * @param {string} text 
     * @returns {Promise<Array<{title: string, content: string}>>}
     */
    async summarize(text) {
        // Dummy implementation: split by paragraphs and take some
        // Real implementation would call an LLM API here.

        const paragraphs = text.split(/\n\s*\n/).filter(p => p.length > 50);
        const slides = [];

        // Title Slide
        slides.push({
            title: "Summary",
            content: "Generated by Paper2Slide"
        });

        // Generate max 5 content slides
        const count = Math.min(paragraphs.length, 5);
        for (let i = 0; i < count; i++) {
            slides.push({
                title: `Section ${i + 1}`,
                content: paragraphs[i].substring(0, 300) + (paragraphs[i].length > 300 ? "..." : "")
            });
        }

        return slides;
    }
};
