var Paper2SlideSummarizer = {
    /**
     * Summarizes the text content into slide-sized chunks.
     * @param {string} text 
     * @returns {Promise<Array<{title: string, content: string}>>}
     */
    async summarize(text) {
        // Split by paragraphs and filter short ones
        const paragraphs = text.split(/\n\s*\n/).filter(p => p.trim().length > 100);
        const slides = [];

        // Title Slide
        slides.push({
            title: "Summary",
            content: "Generated by Paper2Slide"
        });

        // Generate content slides (max 6)
        const count = Math.min(paragraphs.length, 6);
        for (let i = 0; i < count; i++) {
            const para = paragraphs[i].trim();
            slides.push({
                title: `Key Point ${i + 1}`,
                content: para.substring(0, 400) + (para.length > 400 ? "..." : "")
            });
        }

        // Conclusion slide
        slides.push({
            title: "Conclusion",
            content: "Thank you for reading!"
        });

        return slides;
    }
};
